// This file is automatically generated.
// Pleae visit firebase.google.com to get your web app's configuration
export const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

export const isFirebaseEnabled = !!(
  firebaseConfig.apiKey &&
  firebaseConfig.authDomain &&
  firebaseConfig.projectId &&
  firebaseConfig.storageBucket &&
  firebaseConfig.messagingSenderId &&
  firebaseConfig.appId &&
  !firebaseConfig.apiKey.includes('REPLACE_WITH') &&
  !firebaseConfig.apiKey.includes('your-api-key')
);

export const enableVendorDiscovery = process.env.NEXT_PUBLIC_ENABLE_VENDOR_DISCOVERY === 'true';

export const enableGuideDiscovery = process.env.NEXT_PUBLIC_ENABLE_GUIDE_DISCOVERY === 'true';
