// This file is automatically generated.
// Pleae visit firebase.google.com to get your web app's configuration
export const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

export const isFirebaseEnabled = !!(
  firebaseConfig.apiKey &&
  firebaseConfig.projectId &&
  firebaseConfig.apiKey !== 'REPLACE_WITH_YOUR_API_KEY' &&
  !firebaseConfig.apiKey.includes('your-api-key')
);

export const isBuilderMode = process.env.NEXT_PUBLIC_BUILDER_MODE === 'true';

export const enableVendorDiscovery = process.env.NEXT_PUBLIC_ENABLE_VENDOR_DISCOVERY === 'true';
